---
apiVersion: v1
kind: Pod
metadata:
  name: ##POD_NAME##
  labels:
    ##KEY##: ##VALUE##
  ## optional
  namespace: ##NAMESPACE_OPTIONAL##
spec:
  containers: 
  - name: ##CONTAINER_NAME##
    image: ##IMAGE_NAME##
    ports:
      - containerPort:
    resources:
      limits:
        memory: ##"XXMi"##
      requests:
        memory: ##"XXMi"##
    command: ##["COMMAND_VALUE']##
    args: ##["ARG1", "ARG2"]##
