---
apiVersion: v1
kind: Pod
metadata:
  name: ##POD_NAME##
  labels:
    ##KEY##: ##VALUE##
  ##* Optional
  #namespace: ##NAMESPACE_OPTIONAL##
spec:
  containers: 
  - name: ##CONTAINER_NAME##
    image: ##IMAGE_NAME##
    ##* Optional
    #ports:
    #  - containerPort:
    #resources:
    #  limits:
    #    memory: ##"XXMi"##
    #  requests:
    #    memory: ##"XXMi"##
    #command: ##["COMMAND_VALUE']##
    #args: ##["ARG1", "ARG2"]##
